User.create(name: 'Admin', email: 'admin@gmail.com', password: 'superadmin')
Admin.find_or_create_by!(user_id: 1)
State.find_or_create_by!(progress: '未着手')
State.find_or_create_by!(progress: '着手中')
State.find_or_create_by!(progress: '完了')
